- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Start Nginx
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx

- name: Enable PHP processing in Nginx
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: "^#location ~ \\.php$"
    line: "location ~ \\.php$ { fastcgi_pass 127.0.0.1:9000; }"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
