---
# tasks file for dnsmasq
- name: Install dnsmasq
  apt: 
    name=dnsmasq 
    state=present

- name: Copy dnsmasq config
  template: 
    src=dnsmasq.conf.j2
    dest=/etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: Enable and start dnsmasq service
  service: 
    name=dnsmasq 
    state=started
