- name: Add users
  become: yes
  user:
    name: "{{ item.name }}"
    createhome: yes
    shell: /bin/bash
    password: "{{ 'password' | password_hash('sha512') }}"
  with_items: "{{ users }}"

- name: Add SSH keys for users
  become: yes
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  with_items: "{{ users }}"
